config/routes.rb
Rails.application.routes.draw do

  root to: 'favorites#index'

  resources :favorites, only: [:index, :create, :destroy]

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :destroy]

  post "send_sms" => "messages#send_sms", :as => :send_sms, :format => false
  get "receive-sms" => "messages#receive_sms", :as => :receive_sms, :format => false

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	belongs_to :user
	belongs_to :artist

	validates :artist, presence: true

	def self.fetch_user_artist_ids(user_id)
		#Will fetch all the users favorite artists event
		User.find(user_id).favorites.pluck(:seatgeek_artist_id)
	end

	def self.fetch_user_events(artist_ids)
		#Will fetch all the users favorite artists events
		artist_ids.each do artist_id
			Event.fetch_artist_events(artist_id)
		end
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @lat_lon = get_user_ip
    if session[:user_id]
      @user = User.find(session[:user_id])
      @artists = @user.artists
      render 'with_favorites'
    else
      @user = User.create(guest: true)
      @user.password = "guest"
      @user.password_confirmation = "guest"
      @user.latitude = @lat_lon.first
      @user.longitude = @lat_lon.last
      @user.save
      session[:user_id] = @user.id
    end
  end

  def create
    user = User.find(session[:user_id])
    artist = Artist.find_or_initialize_by(seatgeek_id: params[:favorite][:seatgeek_id])
    artist.update(name: params[:favorite][:name], image_url_small: params[:favorite][:image_url_small])
    favorite = Favorite.create(user: user, artist: artist)
    # flash[:notice] = "Artist saved!"
    render :json => { :success => "success", :status_code => "200", :id => favorite.id }
  end

  def destroy
    Favorite.find(params[:id]).destroy
    render :json => { :success => "success", :status_code => "200" }
  end

  private

  def favorite_params
    params.require(:favorite).permit(:name, :seatgeek_id, :image_url_small)
  end
end

app/views/favorites/_favorites.html.erb
<% artists.each do |artist| %>
  <div class="favorites_band_item" fav-id="<%= artist.favorite_id %>">
  <img class="favorites_band_image" src="<%= artist.image_url_small %>">
  <span class="favorites_band_name"><%= artist.name %></span>
  <button class="favorites_band_remove">X</button>
</div>
<% end %>

app/views/favorites/_favorites_menu.html.erb
<%= render "favorites/favorites", artists: @artists %>

<% if @user.guest == false %>
  <%= link_to '<button class="logout">Logout</button>'.html_safe, session_path(session), :method => :delete %>
<% else %>
  <button class="favorites_save">Notify Me!</div>
<% end %>

app/views/favorites/index.html.erb
<div class="row fullWidth">

  <div class="small-9 large-12 columns">
    
    <div class="search_container">
      
      <input type="text" name="artist-search" id="search_box" placeholder="search your favorite artists..."/>
      
      <h2 id="search_message">Start tracking your favorite artists.<br>Get text updates of upcoming shows near you.</h2>
      
      <div id="band_container">
        <div class="local_shows_list"></div>
        <button id="add_button"></button>
      </div>
    
      <h3 class="login">
        <strong><%= link_to "Login", new_session_path, id: "login_link" %></strong> to Edit Favorites
      </h3>

    </div>
    
  </div>

  <div class="small-3 large-0 columns favorites_menu nofaves" id="favorites-menu">
    
    <button class="favorites_save">Notify Me!</div>

  </div>

</div>

app/views/favorites/with_favorites.html.erb
<div class="row fullWidth">

  <div class="small-9 large-12 columns">
  
    <div class="search_with_faves">
      <input type="text" name="artist-search" id="search_box" placeholder="search your favorite artists..."/>
        
      <h2 id="search_message">Start tracking your favorite artists.<br>Get text updates of upcoming shows near you.</h2>
        
      <div id="band_container">
        <div class="local_shows_list"></div>
        <button id="add_band"></button>
      </div>
      
    </div>
  
  </div>

  <div class="small-3 large-0 columns favorites_menu" id="favorites-menu">
    <%= render "favorites_menu" %>
  </div>

</div>